name: deploy to lambda
on: 
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build image
        cmd: |
          docker build .
