name: build, push and deploy image
on: 
  push:
    branches:
      - main

jobs:
  deploy_source:
    name: build, push and deploy image
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build image/
